name: 🙋 Ask a question
description: >
  Ask a question about or get help with OpenAPIDynamic. Beginner
  questions welcome!
labels: [question]
body:
  - type: markdown
    attributes:
      value: >
        This repository hosts issues for the OpenAPIDynamic library.
        It does *not* track feedback on Xcode and other closed source Apple
        developer software such as URLSession itself; please direct it to
        [Feedback Assistant](https://developer.apple.com/bug-reporting) instead.

        ___

        Please use this issue template to ask a question.
  - type: textarea
    attributes:
      label: Question
      description: >
        What are you trying to achieve? What have you tried? What didn't work as expected?
    validations:
      required: true
